version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credpro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context: .  # Use the current directory (where the Dockerfile is located) for building the Spring Boot app
      dockerfile: Dockerfile  # Use the Dockerfile specified above
    container_name: spring_credpro_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/credpro?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql_data:




